### PR TITLE
FOR closes with REPEAT

### PR DESCRIPTION
**Pull request by dgarroDC**

### CODE REVIEW

**Comment by Lartu** [comment]
Thank you very muuuuch!

**Comment by Lartu** [comment]
Please modify the tests or else LDPL compilation will fail with Travis :s

**Comment by dgarroDC** [comment]
Do you mean [this](https://travis-ci.org/Lartu/ldpl/builds/548037961)? That failed because it ran the old tests (using the NEXT keyword).

**Comment by Lartu** [comment]
Yes yes, that's what I meant. They would fail because they use the NEXT keyword haha.

**Pull request merged**
